# This is a basic workflow to help you get started with Actions

name: "NÖ: Download Feuerwehren (Laufend)"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            data/noe/einsatz_feuerwehren.etag
            downloads/pup
          key: ${{ runner.os }}-einsatz-noe-feuerwehren

      - name: Install pup
        run: |
          test -f ./downloads/pup && exit 0
          mkdir ./downloads
          curl -L https://github.com/ericchiang/pup/releases/download/v0.4.0/pup_v0.4.0_linux_amd64.zip -o ./downloads/pup.zip
          unzip downloads/pup.zip -d ./downloads
          chmod a+x ./downloads/pup

      # Runs a single command using the runners shell
      - name: Download data
        run: |
          curl --etag-save ./data/noe/einsatz_feuerwehren.etag \
            --etag-compare ./data/noe/einsatz_feuerwehren.etag \
            https://www.feuerwehr-krems.at/codepages/wastl/wastlmain/Land_FFimEinsatz.asp -o ./downloads/einsatz_feuerwehren.html
          ./downloads/pup -f ./downloads/einsatz_feuerwehren.html 'table tr json{}' | jq -S '. | map(.children | map(.text)[1:])' > ./data/noe/einsatz_feuerwehren.json

      # Runs a set of commands using the runners shell
      - name: Commit and push if changed
        run: |
          git config user.name "GitHub Actions"
          git config user.email "bot@hochstrasser.io"
          git add -A
          timestamp=$(date -u)
          git commit -m "NOE/Feuerwehren: ${timestamp}" || exit 0
          git push
